title: Peoples-Rights.org
description: An organization dedicated to defend civil rights, we protect enforceable right or privilege, which if interfered with by another gives rise to an action for injury.
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
